web:
    build: .
    environment:
        - DB_HOST=postgres
        - DB_NAME=postgres
    links:
        - postgres:postgres
    ports:
        - 8000:80
    volumes:
        - .:/project

postgres:
    image: postgres:latest
    volumes_from:
        - data

data:
    image: postgres:latest
    volumes:
        - /var/lib/postgresql
    command: "true"
